import type { MetadataRoute } from "next";

const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://bluedino.kr";

const routes = [
  "",
  "/cal/calculator",
  "/cal/capital-gains",
  "/cal/compound",
  "/cal/fire",
  "/cal/retirement-tax",
  "/cal/salary-net",
  // "/stocks",
  // "/etf/ranking",
  // "/etf/compare",
  // "/etf/dividend-calendar",
  // "/stocks/AAPL",
  // "/stocks/MSFT",
  // "/stocks/NVDA",
  // "/stocks/AMZN",
  "/info/blog",
  "/info/etc/about",
  "/info/etc/contact",
  "/info/etc/privacy",
  "/info/etc/terms",
  "/info/guide",
  "/info/guide/cashflow-vs-capital-gains",
  "/info/guide/compound-interest",
  "/info/guide/diversification",
  "/info/guide/dividend",
  "/info/guide/dividend-basics",
  "/info/guide/dividend-growth",
  "/info/guide/etf-basics",
  "/info/guide/etf-vs-stocks",
  "/info/guide/fire",
  "/info/guide/fire-calculator-guide",
  "/info/guide/high-dividend-risks",
  "/info/guide/isa-basics",
  "/info/guide/isa-benefits",
  "/info/guide/long-vs-short-term",
  "/info/guide/loss-tax",
  "/info/guide/monthly-dividend-etf-checklist",
  "/info/guide/pension",
  "/info/guide/pension-vs-irp",
  "/info/guide/portfolio-basics",
  "/info/guide/portfolio-mistakes",
  "/info/guide/risk-management",
  "/info/guide/stock-basics",
  "/info/guide/tax",
  "/info/guide/us-stock-tax-basics",
  "/info/guide/why-tax-advantaged-accounts",
  "/info/investment/account-tax",
  "/info/investment/account-tax-step",
  "/info/strategy",
  "/info/strategy/asset-allocation",
  "/info/strategy/dividend",
  "/info/strategy/etf-core-satellite",
  "/info/strategy/market-downturn",
  "/info/strategy/retirement-income",
  "/info/strategy/tax-efficient-investing",
  "/info/videos",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();

  return routes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: now,
    changeFrequency: route === "" ? "weekly" : route.startsWith("/stocks/") ? "weekly" : "monthly",
    priority: route === "" ? 1 : route === "/stocks" || route.startsWith("/stocks/") || route.startsWith("/cal/") || route === "/info/guide" || route === "/info/strategy" ? 0.9 : 0.8,
  }));
}
